data "azurerm_client_config" "current" {}

resource "azurerm_key_vault" "this" {
  name                = "kv-${var.project}-${var.environment}-${local.unique_suffix}"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  tenant_id           = data.azurerm_client_config.current.tenant_id # from the active session, never hardcoded
  sku_name            = var.key_vault_sku

  # RBAC-based authorization (Azure's current recommendation) instead of Key Vault access
  # policies - who can read/write which secret is governed by ordinary azurerm_role_assignment
  # resources below, the same mechanism used for the ACR pull and AKS-related role assignments
  # elsewhere in this configuration.
  enable_rbac_authorization = true

  public_network_access_enabled = false

  tags = local.default_tags
}

# The identity running `terraform apply` needs write access to actually create the secrets
# below - granted narrowly (this vault only, this role only), not via a standing admin
# assignment on the whole subscription.
resource "azurerm_role_assignment" "terraform_operator_kv_admin" {
  scope                = azurerm_key_vault.this.id
  role_definition_name = "Key Vault Administrator"
  principal_id         = data.azurerm_client_config.current.object_id
}

# What the control plane's workload identity (identity.tf) is actually granted: read-only
# access to secret VALUES, nothing else (not key/certificate operations, not vault
# management) - the minimum the Secrets Store CSI driver needs to mount these into the pod.
resource "azurerm_role_assignment" "control_plane_kv_secrets_user" {
  scope                = azurerm_key_vault.this.id
  role_definition_name = "Key Vault Secrets User"
  principal_id         = azurerm_user_assigned_identity.control_plane.principal_id
}

resource "azurerm_private_endpoint" "key_vault" {
  name                = "pe-kv-${local.name_prefix}"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  subnet_id           = azurerm_subnet.private_endpoints.id

  private_service_connection {
    name                           = "key-vault-privateserviceconnection"
    private_connection_resource_id = azurerm_key_vault.this.id
    subresource_names              = ["vault"]
    is_manual_connection           = false
  }

  private_dns_zone_group {
    name                 = "key-vault-dns-zone-group"
    private_dns_zone_ids = [azurerm_private_dns_zone.key_vault.id]
  }

  tags = local.default_tags
}

# --- Secrets ---------------------------------------------------------------------------------
# Every value below is generated by Terraform or read back from the resource that owns it -
# nothing is typed in as a literal anywhere in this repository. This is the ONLY place any of
# these values exist outside of Terraform state (see versions.tf's backend note, and
# .gitignore's *.tfstate exclusion) and the datastores themselves; no Kubernetes Secret, no
# manifest, and no CI variable holds a copy - see README.md's "No secret in any manifest".
#
# Getting these into the pod is the Secrets Store CSI Driver's job (already enabled by
# key_vault_secrets_provider in aks.tf) via a SecretProviderClass that the control plane's
# workload identity (identity.tf) reads through - see README.md, "Wiring Key Vault into the
# cluster", for the exact SecretProviderClass and how it lands as the Kubernetes Secret
# charts/agentplane's controlPlane.secretEnv (values.yaml) references.

resource "azurerm_key_vault_secret" "postgres_password" {
  name         = "postgres-admin-password"
  value        = random_password.postgres_admin.result
  key_vault_id = azurerm_key_vault.this.id
  depends_on   = [azurerm_role_assignment.terraform_operator_kv_admin]
}

resource "azurerm_key_vault_secret" "postgres_url" {
  name         = "postgres-jdbc-url"
  value        = "jdbc:postgresql://${azurerm_postgresql_flexible_server.this.fqdn}:5432/${azurerm_postgresql_flexible_server_database.agentplane.name}"
  key_vault_id = azurerm_key_vault.this.id
  depends_on   = [azurerm_role_assignment.terraform_operator_kv_admin]
}

resource "azurerm_key_vault_secret" "mongo_connection_string" {
  name         = "mongo-connection-string"
  value        = azurerm_cosmosdb_account.this.primary_mongodb_connection_string
  key_vault_id = azurerm_key_vault.this.id
  depends_on   = [azurerm_role_assignment.terraform_operator_kv_admin]
}

resource "azurerm_key_vault_secret" "redis_connection" {
  name         = "redis-primary-key"
  value        = azurerm_redis_cache.this.primary_access_key
  key_vault_id = azurerm_key_vault.this.id
  depends_on   = [azurerm_role_assignment.terraform_operator_kv_admin]
}
