variable "project" {
  description = "Short project name, used as a prefix for every resource name."
  type        = string
  default     = "agentplane"
}

variable "environment" {
  description = "Environment name (dev/staging/prod) - part of every resource name and tag."
  type        = string
  default     = "dev"

  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "environment must be one of: dev, staging, prod."
  }
}

variable "location" {
  description = "Azure region for every resource."
  type        = string
  default     = "eastus2"
}

variable "tags" {
  description = "Extra tags merged onto every resource's default tags (project/environment/managed-by)."
  type        = map(string)
  default     = {}
}

# --- Networking --------------------------------------------------------------------------

variable "vnet_address_space" {
  description = "Address space of the VNet AKS, Postgres (VNet-integrated), and every private endpoint live in."
  type        = string
  default     = "10.42.0.0/16"
}

variable "aks_subnet_cidr" {
  description = "Subnet CIDR for AKS nodes/pods (azure CNI). Must fit inside vnet_address_space."
  type        = string
  default     = "10.42.0.0/20"
}

variable "postgres_subnet_cidr" {
  description = "Delegated subnet CIDR for the VNet-integrated Postgres Flexible Server."
  type        = string
  default     = "10.42.16.0/24"
}

variable "private_endpoint_subnet_cidr" {
  description = "Subnet CIDR for the private endpoints (Redis, Cosmos DB Mongo API, Key Vault, ACR)."
  type        = string
  default     = "10.42.17.0/24"
}

# --- AKS -----------------------------------------------------------------------------------

variable "aks_kubernetes_version" {
  description = <<-EOT
    Kubernetes minor version for AKS (e.g. "1.29"). Check currently-supported versions for your
    region first: `az aks get-versions --location <location> -o table`. Left as an explicit
    variable rather than "always latest" so an upgrade is a deliberate, reviewed change to this
    file, not something that happens silently on the next `terraform apply`.
  EOT
  type        = string
  default     = "1.29"
}

variable "aks_node_count" {
  description = "Node count for the (single) system+user node pool. Split into separate system/user pools for a real production cluster; kept as one pool here to bound this example's scope."
  type        = number
  default     = 3
}

variable "aks_node_vm_size" {
  description = "VM size for AKS nodes."
  type        = string
  default     = "Standard_D4s_v5"
}

# --- Azure Database for PostgreSQL Flexible Server ------------------------------------------

variable "postgres_sku_name" {
  description = "Flexible Server SKU (Azure's <tier>_<compute> naming, e.g. B_Standard_B2s, GP_Standard_D2s_v3)."
  type        = string
  default     = "B_Standard_B2s"
}

variable "postgres_storage_mb" {
  description = "Postgres storage in MB."
  type        = number
  default     = 32768
}

variable "postgres_version" {
  description = "Postgres major version - matches control-plane's Flyway migrations (developed/tested against Postgres 16, see control-plane/docker-compose.yml's postgres:16-alpine)."
  type        = string
  default     = "16"
}

variable "postgres_admin_username" {
  description = "Postgres administrator login name. The password is generated by Terraform (random_password) and stored only in Key Vault - see keyvault.tf."
  type        = string
  default     = "agentplane_admin"
}

# --- Azure Cache for Redis -------------------------------------------------------------------

variable "redis_sku_name" {
  description = "Redis SKU tier: Basic, Standard, or Premium."
  type        = string
  default     = "Standard"
}

variable "redis_family" {
  description = "Redis SKU family: C for Basic/Standard, P for Premium."
  type        = string
  default     = "C"
}

variable "redis_capacity" {
  description = "Redis SKU capacity (size within the family - see Azure's Redis pricing tiers)."
  type        = number
  default     = 1
}

# --- Cosmos DB (Mongo API) ------------------------------------------------------------------

variable "cosmos_consistency_level" {
  description = "Cosmos DB default consistency level."
  type        = string
  default     = "Session"
}

# --- Key Vault -------------------------------------------------------------------------------

variable "key_vault_sku" {
  description = "Key Vault SKU: standard or premium (premium adds HSM-backed keys, not needed here)."
  type        = string
  default     = "standard"
}

# --- Workload identity wiring (must match the Helm release) ----------------------------------

variable "control_plane_namespace" {
  description = "Kubernetes namespace the control plane is deployed into (charts/agentplane's Release.Namespace) - part of the federated identity credential's subject."
  type        = string
  default     = "agentplane"
}

variable "control_plane_service_account_name" {
  description = <<-EOT
    Name of the control plane's ServiceAccount, exactly as the Helm chart names it
    (agentplane.serviceAccountName in charts/agentplane/templates/_helpers.tpl - by default
    "<helm release name>-control-plane"). Must match what's actually deployed, or the federated
    identity credential's subject won't match the token AKS issues to that ServiceAccount and
    every Key Vault read will fail with an auth error, not a "not found" - keep this in sync
    with the Helm release name used for `helm upgrade --install <name> charts/agentplane`.
  EOT
  type        = string
  default     = "agentplane-control-plane"
}
