"""End-to-end mTLS tests against a real local HTTPS server (see conftest.py).

These are deliberately not mocks of ``ssl``/``requests``: a real TLS handshake
happens over a real socket on 127.0.0.1 for every test here, using
short-lived certificates generated by the system ``openssl`` binary.
"""

import json

import pytest

from agentplane_worker.control_plane_client import (
    ControlPlaneClient,
    ControlPlaneClientConfigError,
    MtlsConfig,
)


def test_successful_mtls_report(mtls_server, pki):
    config = MtlsConfig(
        base_url=mtls_server.base_url,
        client_cert=pki.client_crt,
        client_key=pki.client_key,
        ca_bundle=pki.ca_crt,
    )
    client = ControlPlaneClient(config)

    ok = client.report_status("run-1", "SUCCEEDED", message="all good", extra={"steps": 3})

    assert ok is True
    assert len(mtls_server.received) == 1
    path, body = mtls_server.received[0]
    assert path == "/api/v1/internal/runs/run-1/status"
    payload = json.loads(body)
    assert payload["status"] == "SUCCEEDED"
    assert payload["message"] == "all good"
    assert payload["extra"] == {"steps": 3}


def test_wrong_ca_bundle_fails_to_verify_the_server(mtls_server, pki, caplog):
    """The worker's AGENTPLANE_CA_BUNDLE does not contain the CA that issued
    the control plane's server certificate - this must fail closed, not fall
    back to an unverified connection."""
    config = MtlsConfig(
        base_url=mtls_server.base_url,
        client_cert=pki.client_crt,
        client_key=pki.client_key,
        ca_bundle=pki.rogue_ca_crt,  # wrong CA on purpose
    )
    client = ControlPlaneClient(config)

    with caplog.at_level("ERROR"):
        ok = client.report_status("run-1", "SUCCEEDED")

    assert ok is False
    assert mtls_server.received == []  # request never actually completed
    assert any("mTLS handshake failed" in record.message for record in caplog.records)


def test_server_rejects_a_client_certificate_from_an_untrusted_ca(mtls_server, pki, caplog):
    """Mirror image of the above: the *control plane* does not trust this
    worker's client certificate (signed by an unrelated CA)."""
    config = MtlsConfig(
        base_url=mtls_server.base_url,
        client_cert=pki.rogue_client_crt,
        client_key=pki.rogue_client_key,
        ca_bundle=pki.ca_crt,
    )
    client = ControlPlaneClient(config)

    with caplog.at_level("ERROR"):
        ok = client.report_status("run-1", "SUCCEEDED")

    assert ok is False
    assert mtls_server.received == []


def test_missing_client_cert_file_raises_config_error_eagerly(tmp_path, pki):
    config = MtlsConfig(
        base_url="https://127.0.0.1:1",
        client_cert=tmp_path / "does-not-exist.crt",
        client_key=pki.client_key,
        ca_bundle=pki.ca_crt,
    )
    with pytest.raises(ControlPlaneClientConfigError, match="client certificate"):
        ControlPlaneClient(config)


def test_mtls_config_from_env_reports_every_missing_variable(monkeypatch):
    for var in (
        "AGENTPLANE_CONTROL_PLANE_URL",
        "AGENTPLANE_CLIENT_CERT",
        "AGENTPLANE_CLIENT_KEY",
        "AGENTPLANE_CA_BUNDLE",
    ):
        monkeypatch.delenv(var, raising=False)

    with pytest.raises(ControlPlaneClientConfigError) as exc_info:
        MtlsConfig.from_env()

    message = str(exc_info.value)
    for var in (
        "AGENTPLANE_CONTROL_PLANE_URL",
        "AGENTPLANE_CLIENT_CERT",
        "AGENTPLANE_CLIENT_KEY",
        "AGENTPLANE_CA_BUNDLE",
    ):
        assert var in message


def test_mtls_config_from_env_succeeds_when_all_vars_set(monkeypatch, pki, tmp_path):
    monkeypatch.setenv("AGENTPLANE_CONTROL_PLANE_URL", "https://control-plane:8443")
    monkeypatch.setenv("AGENTPLANE_CLIENT_CERT", str(pki.client_crt))
    monkeypatch.setenv("AGENTPLANE_CLIENT_KEY", str(pki.client_key))
    monkeypatch.setenv("AGENTPLANE_CA_BUNDLE", str(pki.ca_crt))

    config = MtlsConfig.from_env()

    assert config.base_url == "https://control-plane:8443"
    assert config.client_cert == pki.client_crt
